# Generated by Django 6.0.5 on 2026-05-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='exported_to_csv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
