# Generated by Django 6.0.5 on 2026-05-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_lead_exported_to_csv_lead_is_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='activity_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_active_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
