# Generated by Django 6.0.5 on 2026-05-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0007_siteconfig_llm_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='randomize_delays',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('follow_up', 'Follow Up'), ('profile_view', 'Profile View'), ('search', 'Search')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('check_pending', 'Check Pending'), ('follow_up', 'Follow Up'), ('export', 'Export')], max_length=20),
        ),
    ]
